%YAML:1.0

NvDCF:
  useUniqueID: 0
  maxTargetsPerStream: 150

  MiscConfig:
    useColorNames: 1

  FilterConfig:
    useTrackletFiltering: 1

  AssociationConfig:
    dataAssociationThreshold: 0.2
    associationMatcherType: 0
    thresholdMahalanobis: 9.4877

  StateEstimatorConfig:
    smoothingEnabled: 1
    numIter: 2
    noiseWeightVar: 0.01
    noiseWeightStd: 0.1

  TargetManagementConfig:
    enableBboxUnClipping: 1
    maxTargetsPerStream: 150
    minDetectorConfidence: 0.3
    probationAge: 3
    earlyTerminationAge: 1
    maxShadowTrackingAge: 30
    useEarlyTermination: 1
    useLatency: 0
```

### 5. **configs/labels.txt**
```
person
bicycle
car
motorcycle
airplane
bus
train
truck
boat
traffic light
fire hydrant
stop sign
parking meter
bench
bird
cat
dog
horse
sheep
cow
elephant
bear
zebra
giraffe
backpack
umbrella
handbag
tie
suitcase
frisbee
skis
snowboard
sports ball
kite
baseball bat
baseball glove
skateboard
surfboard
tennis racket
bottle
wine glass
cup
fork
knife
spoon
bowl
banana
apple
sandwich
orange
broccoli
carrot
hot dog
pizza
donut
cake
chair
couch
potted plant
bed
dining table
toilet
tv
laptop
mouse
remote
keyboard
cell phone
microwave
oven
toaster
sink
refrigerator
book
clock
vase
scissors
teddy bear
hair drier
toothbrush
```

### 6. **model_repository/yolo11n/config.pbtxt**
```
name: "yolo11n"
platform: "tensorrt_plan"
max_batch_size: 0

input [
  {
    name: "images"
    data_type: TYPE_FP32
    dims: [1, 3, 640, 640]
  }
]

output [
  {
    name: "output0"
    data_type: TYPE_FP32
    dims: [1, 84, 8400]
  }
]

instance_group [
  {
    count: 1
    kind: KIND_GPU
  }
]

dynamic_batching {
  max_queue_delay_microseconds: 100
}
```

### 7. **model_repository/rf-detr-nano/config.pbtxt**
```
name: "rf-detr-nano"
platform: "tensorrt_plan"
max_batch_size: 0

input [
  {
    name: "images"
    data_type: TYPE_FP32
    dims: [1, 3, 640, 640]
  }
]

output [
  {
    name: "output0"
    data_type: TYPE_FP32
    dims: [1, 300, 6]
  }
]

instance_group [
  {
    count: 1
    kind: KIND_GPU
  }
]

dynamic_batching {
  max_queue_delay_microseconds: 100
}