%YAML:1.0

NvDCF:
  useUniqueID: 0
  maxTargetsPerStream: 150

  MiscConfig:
    useColorNames: 1

  FilterConfig:
    useTrackletFiltering: 1

  AssociationConfig:
    dataAssociationThreshold: 0.2
    associationMatcherType: 0
    thresholdMahalanobis: 9.4877

  StateEstimatorConfig:
    smoothingEnabled: 1
    numIter: 2
    noiseWeightVar: 0.01
    noiseWeightStd: 0.1

  TargetManagementConfig:
    enableBboxUnClipping: 1
    maxTargetsPerStream: 150
    minDetectorConfidence: 0.3
    probationAge: 3
    earlyTerminationAge: 1
    maxShadowTrackingAge: 30
    useEarlyTermination: 1
    useLatency: 0
